### ISSUE TITLE
Rust upgrade to LLVM6 breaks wee_alloc

### ISSUE THREAD

**Issue by Mirclus** [fitzgen/wee_alloc#16]
*wee_alloc* fails to build with the latest nightly (and possibly yesterdays as well) and most likely will continue to fail with upcoming versions (target: wasm32-unknown-unknown):

```
Intrinsic has incorrect return type!
void (i32)* @llvm.wasm.grow.memory.i32
LLVM ERROR: Broken function found, compilation aborted!
```

This is most likely caused by the upgrade to LLVM 6 (https://github.com/rust-lang/rust/pull/47828), which [changed](https://github.com/rust-lang/llvm/commit/97c35d16c63ec9163561b18b4971095d221c9910#diff-b61c5925c6c974816011969a2adb8c0f) the return type of this intrinsic.

**Comment by fitzgen** [comment]
Thanks foir the heads up! Should be a pretty easy fix if you're interested in contributing. Just need to change the return type in `imp_wam32.rs` and make the `alloc_pages` function take advantage of the return type.
