### ISSUE TITLE
Support allocations with alignment greater than a word

### ISSUE THREAD

**Issue by masonforest** [fitzgen/wee_alloc#29]
### Summary

When I create a `Vec` of `Enums` that have a `u64` field on them I get the following error: `RuntimeError: unreachable `

### Steps to Reproduce

* `git clone https://github.com/masonforest/wee_alloc_vec_of_enums_bug`
* `cd wee_alloc_vec_of_enums_bug`
* `cargo rustc --target wasm32-unknown-unknown --lib -- -O && node run.js`

### Actual Results

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
(node:6108) UnhandledPromiseRejectionWarning: RuntimeError: unreachable
    at run (wasm-function[7]:1)
    at run (/Users/masonf/src/wee_alloc_vec_of_enums_bug/run.js:20:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
(node:6108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected Results

````
Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
````

**Comment by fitzgen** [comment]
Thanks for filing a bug! Does it also reproduce if you compile with `--release`? The `wasm32-unknown-unknown` target is known to be buggy if you don't compile with `--release`.

**Comment by masonforest** [comment]
👋 @fitzgen  Thanks for all your work on this! :D

Hmmm, I tried to compile with `--release` and got the same error.


````
    $ cargo rustc --target wasm32-unknown-unknown --lib --release -- && node run.js
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/fitzgen/wee_alloc`
    Compiling memory_units v0.4.0
    Compiling rlibc v1.0.0
    Compiling wee_alloc v0.1.0 (https://github.com/fitzgen/wee_alloc#792f27c1)
    Compiling wee_alloc_vec_of_enums_bug v0.1.0 (file:///Users/masonf/tmp/wee_alloc_vec_of_enums_bug)
    Finished dev [unoptimized + debuginfo] target(s) in 1.22 secs
(node:6678) UnhandledPromiseRejectionWarning: RuntimeError: unreachable
    at run (wasm-function[7]:1)
    at run (/Users/masonf/tmp/wee_alloc_vec_of_enums_bug/run.js:20:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
    (node:6678) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error 
    originated either by throwing inside of an async function without a catch block, or by rejecting a 
    promise which was not handled with .catch(). (rejection id: 1)
    (node:6678) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In 
    the future, promise rejections that are not handled will terminate the Node.js process with a non-
    zero exit code.
````


I should have put in the original bug: This works if you change the `u64` type to `u32` or if you remove the wrapping `Vec`. I'm pretty new to Rust and WASM. There's definitely a chance this bug is somewhere else in the stack. Let me know if there's anything else I can do to help track this down. :)

**Comment by fitzgen** [comment]
Running `wasm-objdump -d target/wasm32-unknown-unknown/release/wee_alloc_vec_of_enums_bug.wasm` yields:

```
...
000188 <run>:
 00018a: 00                         | unreachable
 00018b: 00                         | unreachable
 00018c: 0b                         | end
```

o_O

I'm thinking this might be miscompilation.

**Comment by fitzgen** [comment]
Ok, what is happening here is that the layout is calling for alignment of eight bytes, which is larger than a word (four bytes on wasm32) and not currently supported. The optimizer can see statically that this allocation is going to return an error which turns into an `unreachable` and is performing transformations that take advantage of that.

**Comment by fitzgen** [comment]
So I guess we do really need to support greater than word alignemnts :)

**Comment by masonforest** [comment]
Cool. In the mean time I can represent these `u64`s as a Vec of `u8`s 👍

**Comment by fitzgen** [comment]
I have a half working implementation. Size classes are problematic because the cell header precedes the data. Thinking.
