### ISSUE TITLE
Is this crate is ready for use?

### ISSUE THREAD

**Issue by pepyakin** [fitzgen/wee_alloc#4]
What is left to publish this on crates.io?

**Comment by fitzgen** [comment]
Hi @pepyakin :)

I'm working on #1 and #2 right now, and once they're fixed, then I'll write up an announcement and publish to crates.io.

**Comment by pepyakin** [comment]
Cool!
But is NonNull is really stable now?

**Comment by fitzgen** [comment]
If I've gotten my timeline correct, it is stable (ie, no feature flags required) in nightly and beta right now, and will be stable in release after the next step of the trains.

Note that replacing allocators is still nightly anyways, so `NonNull` isn't keeping this from being usable on non-nightly channels.

**Comment by pepyakin** [comment]
Ah, I see. That explains why I can't see it on stable docs.

**Comment by fitzgen** [comment]
Just published to crates.io. Haven't written up an announcement yet.
